version: '3.4'

networks:
  defult:
    name: 'defult'

services:
  db:
    image: postgres:15
    environment:
      -POSTGRES_DB : geodjango
      -POSTGRES_USER : geodjangouser
      -POSTGRES_PASSWORD : MSH1377
    volumes:
      - POSTGRESDATA:/var/lib/postgresql/data/
  app:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/backend/backend_api
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
    ports:
      - "8000:8000"
    environment:
      - .env
    depends_on:
      - db



volumes:
  POSTGRESDATA:
  .:
  static_volume:
  media_volume:
