# Generated by Django 5.2.1 on 2025-07-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='propertyModel',
            fields=[
                ('case_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('landuse', models.CharField(max_length=10)),
                ('ptype', models.CharField(max_length=10)),
                ('price', models.BigIntegerField(verbose_name='قیمت در ازا هر مترمربع')),
                ('area', models.IntegerField(verbose_name='مساحت')),
                ('Cyear', models.CharField(verbose_name='سال ساخت')),
                ('mortgage', models.BigIntegerField(verbose_name='رهن')),
                ('rent', models.BigIntegerField(verbose_name='اجاره')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('mahale', models.CharField(max_length=100, verbose_name='محله')),
                ('exp', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('link', models.CharField(max_length=500)),
                ('date_time', models.DateTimeField(max_length=500)),
                ('shape', models.BooleanField(default=False)),
            ],
        ),
    ]
