# Generated by Django 5.2.1 on 2025-07-19 07:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MahalatTehran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mahal', models.CharField(max_length=50)),
                ('reg_no', models.IntegerField()),
                ('shape_le_1', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='masages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('txtmasages', models.CharField(verbose_name='پیام')),
            ],
        ),
        migrations.CreateModel(
            name='MTPPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landuse', models.CharField(max_length=10)),
                ('ptype', models.CharField(max_length=10)),
                ('price', models.BigIntegerField()),
                ('mortgage', models.BigIntegerField(default=0)),
                ('rent', models.BigIntegerField(default=0)),
                ('name_mahal', models.CharField(max_length=50)),
                ('reg_no', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
