# Generated by Django 5.1.4 on 2024-12-09 19:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTPPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landuse', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('mortgage', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('name_mahal', models.CharField(max_length=50)),
                ('reg_no', models.IntegerField()),
                ('shape_le_1', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
