# Generated by Django 5.1.4 on 2024-12-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_mtppolygon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtppolygon',
            name='shape_area',
        ),
        migrations.RemoveField(
            model_name='mtppolygon',
            name='shape_le_1',
        ),
        migrations.AlterField(
            model_name='mtppolygon',
            name='mortgage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mtppolygon',
            name='rent',
            field=models.IntegerField(default=0),
        ),
    ]
