# Generated by Django 5.1.4 on 2024-12-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_remove_mtppolygon_shape_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='masages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('txtmasages', models.CharField(verbose_name='پیام')),
            ],
        ),
    ]
