# Generated by Django 5.1.4 on 2025-01-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_masages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mtppolygon',
            old_name='type',
            new_name='ptype',
        ),
    ]
